import type { PlanEntry } from "./types";

export const PLAN_FIXTURES: PlanEntry[] = [
  {
    type: "seq",
    id: "email",
    name: "Email campaign",
    chain: "A → B",
    bets: [
      {
        id: "demo-bet-005",
        name: "Subject-line A/B",
        surface: "email · open rate",
        metric: "open rate",
        status: "won",
        start: 0,
        dur: 2,
        resolved: true,
      },
      {
        id: "demo-bet-004",
        name: "Email body CTA above fold",
        surface: "email · 7-day login",
        metric: "7-day login",
        status: "running",
        start: 2,
        dur: 3,
        dep: "demo-bet-005",
      },
    ],
  },
  {
    type: "solo",
    bet: {
      id: "demo-bet-008",
      name: "Plan-picker above fold",
      surface: "pricing page",
      metric: "checkout-start",
      status: "won",
      start: 1,
      dur: 4,
      resolved: true,
    },
  },
  {
    type: "seq",
    id: "checkout",
    name: "Checkout sequence",
    chain: "D → F",
    bets: [
      {
        id: "demo-bet-003",
        name: "CTA color test",
        surface: "pricing page",
        metric: "checkout-start",
        status: "locked",
        start: 4,
        dur: 2,
      },
      {
        id: "plan-future-1",
        name: "Winning CTA + copy",
        surface: "pricing page",
        metric: "checkout-start",
        status: "draft",
        start: 6,
        dur: 2,
        dep: "demo-bet-003",
      },
    ],
  },
  {
    type: "solo",
    bet: {
      id: "demo-bet-006",
      name: "Onboarding step reduction",
      surface: "onboarding",
      metric: "completion rate",
      status: "won",
      start: 3,
      dur: 3,
      resolved: true,
    },
  },
];
